name: python Artifact demo

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Create-Artifact:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Python Version
        run: python3 --version

      - name: Run Python Code
        run: python3 app.py

      - name: Who Generated File
        run: cat results.txt

      - name: Upload result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-result-file
          path: results.txt
